### ISSUE TITLE
deprecation warning from tally()

### ISSUE THREAD

**Issue by nicholasjhorton** [ProjectMOSAIC/mosaicCore#30] opened 2020-07-05 14:38 UTC
``` r
suppressPackageStartupMessages(library(mosaic))
tally(HELPrct$homeless)
#> Warning: `data_frame()` is deprecated as of tibble 1.1.0.
#> Please use `tibble()` instead.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_warnings()` to see where this warning was generated.
#> X
#> homeless   housed 
#>      209      244
```

<sup>Created on 2020-07-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Note that the warning doesn't display if you run:

`tally(~ HELPrct$homeless)`
or
`tally(~ homeless, data = HELPrct)`

**Comment by rpruim** [comment] 2020-07-06 00:31
Interesting.

This should have been fixed by https://github.com/ProjectMOSAIC/mosaicCore/commit/551490f3a3bd96dfa11953f3fe8c981279b179bf (a year ago).  I can't reproduce locally, but can on an older installation that should be more recent than the fix.

For starters, can you install mosaicCore from github and let me know if the problem goes away?

**Comment by VectorPosse** [comment] 2020-10-06 17:43
My students are seeing this too, using the `prop` function. (I suspect because it calls `tally`.) Even though it's clearly labeled as a "warning", I still got several panicked emails from students thinking they did something wrong.  :-)

**Comment by rpruim** [comment] 2020-10-06 22:30
@VectorPosse , do you have the current version of mosaicCore?  I can't recreate this problem and I'm unable to locate `data_frame()` in the code base.

**Comment by VectorPosse** [comment] 2020-10-06 22:42
I assumed so since I upgraded everything at the beginning of the semester,
but if the change is recent, then I'm not sure. I've installed the package
again, but I'll need to wait a few more hours to test it (since the warning
says it only appears after eight hours?!?).

**Comment by rpruim** [comment] 2020-10-07 00:09
Thanks.  Let me know how it comes out.

Your clock will restart if you restart R, so if you are impatient, you can restart R and then do your test at any time.

We had hoped to get the update to CRAN by late August, but it was into September before the update was available on CRAN.  There will likely be another minor update coming in the next week or so to fix bug in `df_stats()` when you request the long format.

**Comment by VectorPosse** [comment] 2020-10-07 02:22
Got it. Yes, it all works now! Thanks!

**Closed as completed** 2020-10-07 02:44 UTC
